### ISSUE TITLE
Bugs in theme responsiveness - images disappearing fully or partially on different screen sizes, etc.

### ISSUE THREAD

**Issue by ctapnec** [creativetimofficial/ct-now-ui-kit-pro#11]
When the @media screen size is with phone or tablet dimensions, header sections are starting to bug - text and images disappear or are being sliced. Please, refer to the attached images:
![a](https://user-images.githubusercontent.com/11669622/37355950-95da7bb6-26ed-11e8-84a4-127eb2e8dc73.jpg)
![b](https://user-images.githubusercontent.com/11669622/37355963-9d68d15c-26ed-11e8-99c6-bdf74f967ed2.jpg)
![c](https://user-images.githubusercontent.com/11669622/37355970-a20d3996-26ed-11e8-94f5-083ef3519855.jpg)

**Comment by dragosct10** [comment]
Hi, @ctapnec! Thank you for using our product and sorry for the late response. Please, can you tell us on which browser did you test it? Regards, Dragos

**Comment by ctapnec** [comment]
Greetings,

My OS, Browser, JS Engine and Flash versions + the user-agent string:

**Comment by ctapnec** [comment]
Greetings,

I just wanted to check - would you be professionals and fix the product you're selling, or should I forget about the money I spent on this theme and choose another one, which is at least fully responsive?

Regards,
Georgi

**Comment by ctapnec** [comment]
Greetings,

Thank you very much and sorry for the sour language - I really needed to find out whether I would be able to use this theme or to do a switch - my customers are dealing mostly with mobile devices and I cannot afford to utilize non-responsive design.

Regards,
Georgi

**Comment by dragosct10** [comment]
Hi, @ctapnec! Please use instead of the class `.content-center` the class `.content`. Hope this will fix the issue for you. Let us know if everything is working fine. Regards, Dragos

**Comment by ctapnec** [comment]
Greetings,

Yes, this seems to totally solve the problem. Thank you very much!

Regards,
Georgi
