### ISSUE TITLE
Duplicate imports

### ISSUE THREAD

**Issue by peiche** [creativetimofficial/ct-now-ui-kit-pro#13]
On lines 61 and 65, there is the same line:

```
@import "now-ui-kit/sections";
```

And on lines 63 and 67, there is the same line:

```
@import "now-ui-kit/responsive";
```

Please remove the duplicate lines.

**Comment by dragosct10** [comment]
Hi, @peiche! Thank you for your observation. We will fix this in the next release. Regards, Dragos
