### ISSUE TITLE
Non-overridable variables

### ISSUE THREAD

**Issue by peiche** [creativetimofficial/ct-now-ui-kit-pro#14]
In the file `_variables.scss`, the variable `$sans-serif-family` is not overridable. Please add the property `!default` to it.

While I'm looking at it, there are a number of other variables that are not overridable.

**Comment by dragosct10** [comment]
Hi, @peiche! Thank you for using our product. Yes, you are right we will check this issue and we will fix it in the next update. Regards, Dragos
