### ISSUE TITLE
multipage form next previous button not working

### ISSUE THREAD

**Issue by yksmbkkr** [creativetimofficial/ct-now-ui-kit-pro#16]
No multipage form component is included in your template.
So I am trying to create one using navigation tab.
For this purpose I am trying to add next and previous button using jquery script but its not working.
Script I am using is 

 $('.btnNext').click(function(){
  $('.nav-tabs > .active').next('li').find('a').trigger('click');
});

  $('.btnPrevious').click(function(){
  $('.nav-tabs > .active').prev('li').find('a').trigger('click');
});

What should I do ?
![js](https://user-images.githubusercontent.com/26028128/38102807-fa70d744-33a1-11e8-8f38-418d4533082a.JPG)
![html](https://user-images.githubusercontent.com/26028128/38102814-fe8f7c86-33a1-11e8-8c8e-95b9dee9f9ec.JPG)

**Comment by dragosct10** [comment]
Hi, @yksmbkkr! Thank you for using our product. I think you try to build something like the wizard from the our [Now UI Dashboard](https://demos.creative-tim.com/now-ui-dashboard-pro/examples/forms/wizard.html). Regards, Dragos
