### ISSUE TITLE
panel-header and content divs overlap

### ISSUE THREAD

**Issue by natesnapp** [creativetimofficial/ct-now-ui-kit-pro#17]
I'm seeing text in the content panel get cut off because of overlap between the panel header div and the content. Also, it appears that the panel is too large for just the nav bar and is only creating empty space. How can the empty space be taken back for single page content?

![screen shot 2018-04-12 at 4 01 59 pm](https://user-images.githubusercontent.com/2713065/38708679-452a061e-3e6c-11e8-9f9b-4f2cca85e9a0.png)
![screen shot 2018-04-12 at 4 01 40 pm](https://user-images.githubusercontent.com/2713065/38708693-50ea239e-3e6c-11e8-9047-f89de1b136c1.png)
![screen shot 2018-04-12 at 4 02 13 pm](https://user-images.githubusercontent.com/2713065/38708704-5e96579c-3e6c-11e8-88d2-539ee8ea0507.png)

**Comment by dragosct10** [comment]
Hi, @natesnapp! Thank you for using our product. From what I noticed you have the Vue version, right? Regards, Dragos

**Comment by natesnapp** [comment]
That is correct.

**Comment by natesnapp** [comment]
It appears this is partially avoided when using the card div (which may be the intention, and user should assume content is always meant to be in one of these). In my case, I can make the card background transparent (also have some bootstrap involved, it looks like) and then text sits a lot better.
<img width="632" alt="screen shot 2018-04-13 at 11 16 11 pm" src="https://user-images.githubusercontent.com/2713065/38776052-93ee11ac-4045-11e8-87a6-1bfb1a0835f5.png">

**Comment by dragosct10** [comment]
Hi! We put on the .content div the property margin with value -30px and this cause the problem, but we put this for a better visual style, but you can remove that property from the div and then you will not have this problem anymore. Regards, Dragos
