### ISSUE TITLE
Login page doesn't work

### ISSUE THREAD

**Issue by fleitz** [creativetimofficial/ct-now-ui-kit-pro#20]
https://demos.creative-tim.com/now-ui-kit-pro/examples/login-page.html

Browser:
Chrome Version 66.0.3359.117 (Official Build) (64-bit)

OS:
macOS 10.13.4

Now UI Pro Version 1.2.0

Actual Behavior:
Buttons / forms / links are not clickable, nothing other than the nav bar is clickable, even the footer.

Expected Behavior:
Buttons / forms / links are clickable, and work.

**Comment by dragosct10** [comment]
Hi, @fleitz! Thank you for using our product. To fix this please add these properties: 

```css
   .page-header .container{
      position: relative; 
   }
```

We will fix this also in the next update.

Regards, 
Dragos
