### ISSUE TITLE
Navbar toggler doesnt work and button not showing inline

### ISSUE THREAD

**Issue by cmoyo** [creativetimofficial/ct-now-ui-kit-pro#21]
Hi,

I have been trying to get the navbar-toggler working for me based on the template, but it doesn't seem to work for me. 

Additionally, the button that I tried to add in line with the form group won't stay in line.
[base.txt](https://github.com/creativetimofficial/now-ui-kit-pro/files/1998979/base.txt)
![2018-05-14 00_16_38-headhi](https://user-images.githubusercontent.com/37601027/39972281-2a5aaf10-570c-11e8-92ac-f6edbb4db3a1.png)

**Comment by dragosct10** [comment]
Hi, @cmoyo! Thank you for using our product. Please give us a link to your project to see what is the problem. Regards, Dragos

**Comment by cmoyo** [comment]
Hi @dragosct10 here is the link https://github.com/cmoyo/headi/invitations

**Comment by dragosct10** [comment]
Hi, @cmoyo! You give access to your project but please how I start the server? Regards, Dragos

**Comment by cmoyo** [comment]
Hi @dragosct10, try this in your commandline prompt

# cd PycharmProjects\headi\
# venv\Scripts\activate.bat
# python manage.py runserver

Website should run on localhost:8000

I hope this is helpful. I just started playing around with the now-ui-kit and I was trying to work off the template provided.

**Comment by cmoyo** [comment]
Hi @dragosct10 

I am under some time pressure. Did you get to the bottom of the issues?

Thanks

**Comment by dragosct10** [comment]
Hi, @cmoyo! I tried to start the server but without success. Please see the error below: 

![screen shot 2018-05-21 at 17 17 07](https://user-images.githubusercontent.com/17456857/40312233-ed431300-5d1a-11e8-8b0b-a17fb0f930d2.png)

Regards,
Dragos

**Comment by cmoyo** [comment]
Hi @dragosct10 , please make sure that you have activated the virtual environment correctly .

Secondly please make sure that you have Django 2.0.5 and python 3.6.5 installed on your machine.

**Comment by dragosct10** [comment]
Hi, @cmoyo! It takes me to much time to open the server because now I have another error after I installed django and python to the latest version. Please, can you send us a video to see the issue that you have? Regards, Dragos

**Comment by dragosct10** [comment]
Hi! Yes, of course, you can send me at dragos@creative-tim.com. Regards, Dragos

**Comment by cmoyo** [comment]
@dragosct10 I have sent you the file via wetransfer. Regards, Cyndi

**Comment by dragosct10** [comment]
Yes, I saw the video and please tell me do you have some errors in your console because it's obvious that the function that it's called when you click on the navbar-toggle it's not called and this is from two reasons, first will be some errors in your console that stop the function to work properly or second you don't have the now-ui-kit.js file. Regard on the button that it's not vertically aligned you check the button in browser inspect element for something like margin-top css property? 

Regards, 
Dragos
