### ISSUE TITLE
ProfilePage of Pro version is not properly responsive

### ISSUE THREAD

**Issue by yksmbkkr** [creativetimofficial/ct-now-ui-kit-pro#22]
I am working with pro version of now ui kit.
I am using profile page template but there is issue with header.
Profile Picture is going out of screen and data regarding comments and bookmark is also out of view.
Attaching the image to show the issue.
![tim-profile](https://user-images.githubusercontent.com/26028128/40281519-b78fe6b0-5c80-11e8-9382-a0a672854f8d.jpg)

**Comment by yksmbkkr** [comment]
@dragosct10  open the page in firefox browser and press ctrl+shift+m (on windows) by doing so the browser will enter in responsive design mode and will emulate mobile screen alternatively you can open page on any mobile device to reproduce the issue.

**Comment by dragosct10** [comment]
Hi, @yksmbkkr! You tried to see test this also on a mobile or tablet, too? I saw that on devices the elements look good, only in the responsive mode of the browser, it happens that.

Regards,
Dragos
