### ISSUE TITLE
navbar-collapse background image responsive deadzone

### ISSUE THREAD

**Issue by nanodrive** [creativetimofficial/ct-now-ui-kit-pro#24]
Visit https://demos.creative-tim.com/now-ui-kit/index.html
Resize the window from 992px-1008px and the background image will display on the screen on desktop size. The background image should only be visible on small screen.
![image](https://user-images.githubusercontent.com/6341206/41290177-0295dd36-6e1a-11e8-824d-525d588bac6c.png)

This issue also affects the pro version.
The problem is in the `initNavbarImage()`  function. 
`$(window).width()` does not account for the scrollbar width, so it's off by about 17px consistently.

A hacky workaround is to reduce the threshold from 991 to 974.
`if ($(window).width() < 974 || $('body').hasClass('burger-menu')) `

But it should really be fixed the proper way by the framework.

**Comment by dragosct10** [comment]
Hi, @nanodrive! Thank you for using our product and thank you for this issue. On the MacBook, I saw that the issue it's not present, but on Windows yes you are right the navbar is colored. We will fix this properly and we will put the fix in the next update which will be on 22 June. Regards, Dragos
