### ISSUE TITLE
-webkit-fill-available to stretch

### ISSUE THREAD

**Issue by peiche** [creativetimofficial/ct-now-ui-kit-pro#25]
Running Now UI styles through the latest Autoprefixer, I get this warning:

```
autoprefixer: _responsive.scss:348:6: Replace fill-available to stretch, because spec had been changed
```

**Comment by dragosct10** [comment]
Hi, @peiche! Thank you for using our product. You can replace the property `fill-available` with the property `stretch` and that's it. Don't worry the property fill-available it's working anyway. Regards, Dragos

**Comment by peiche** [comment]
I already did. Since the spec has changed, are you going to update for the next version?

**Comment by dragosct10** [comment]
Hi! Yes, we will add this in the next update, I already mark this issue with a bug label. Regards, Dragos
