### ISSUE TITLE
Dead example icons link

### ISSUE THREAD

**Issue by peiche** [creativetimofficial/ct-now-ui-kit-pro#26]
On the Pro demo [Nucleo Icons page](https://demos.creative-tim.com/now-ui-kit-pro/docs/1.0/components/nucleo-icons.html), the [example icons link](https://demos.creative-tim.com/now-ui-kit-pro/nucleo-icons.html) is a 404.

**Comment by dragosct10** [comment]
Hi, @peiche! Thank you for using our product. Now the link it's working. 

Regards,
Dragos
