### ISSUE TITLE
Missing image asset

### ISSUE THREAD

**Issue by finkbg** [creativetimofficial/ct-now-ui-kit-pro#3]
This has been an issue in 1.0.1 and I now noticed it's the same in 1.1 - 

This relative module was not found:

* ../img/ink.png in ./node_modules/css-loader?{"minimize":false,"sourceMap":true,"importLoaders":0}!./node_modules/resolve-url-loader?{"sourceMap":true}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./assets/scss/now-ui-kit.scss

ink.png is not there. The temp fix is to remove it from .//scss/now-ui-kit/plugins/_plugin-isometricGrids.scss:255

Cheers!

**Comment by cregx** [comment]
The issue is still there in Version 1.2.0

**Comment by dragosct10** [comment]
Hi! Thank you for using our product. We will release an update in about 1-2 weeks and we will fix this problem. Regards, Dragos
