### ISSUE TITLE
Equal Height Cards

### ISSUE THREAD

**Issue by ajarti** [creativetimofficial/ct-now-ui-kit-pro#32]
Hi all,

 I have looked everywhere and I cannot seam to find any documentation on equalizing the height of adjacent cards.

In the demo, screengranbs etc, the cards always have the same number of lines of content, thus look amazing.  How does one ensure there is some aligment when for example one card has 3 line of content and the next 2.  I have used Bootstraps align-self-stretch which makes the cards the same height in a grid, but the footer/header will float and not align to the top bottom etc on cards with less content. So basically I want to keep a consistant look.

I hope this makes sense, thanks in advance.

**Comment by dragosct10** [comment]
Hi, @ajarti! Thank you for using our products. A safe trick that I could say to you it's to put a min-height on your parent `.card` div and in this way you can control your card height. 

Regards, 
Dragos

**Comment by UisgeBeatha436** [comment]
I have three cards in a row, and solved it via:
`<article class="card h-100" style="width: 20rem;">` 
h-100 did do the trick for me.
