### ISSUE TITLE
Some links don't display when they have the navbar-right class

### ISSUE THREAD

**Issue by KonScyence** [creativetimofficial/ct-now-ui-kit-pro#37]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
I would like all links (So login and signup) to also appear in the menu of small devices

# Current Behavior

**Regular menu**
![menu1](https://user-images.githubusercontent.com/27307704/48980882-a9416600-f09c-11e8-86b4-7f5d11db3907.PNG)

**Small menu**
![menu2](https://user-images.githubusercontent.com/27307704/48980883-a9416600-f09c-11e8-8b9e-0f96289b8838.PNG)

## Steps to Reproduce

```
<nav class="navbar navbar-expand-lg bg-white fixed-top navbar-transparent" color-on-scroll="500">
    <div class="container">
      <div class="navbar-translate">
        <a class="navbar-brand" href="#pablo">fe</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-bar bar1"></span>
          <span class="navbar-toggler-bar bar2"></span>
          <span class="navbar-toggler-bar bar3"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#pablo">
              1
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#pablo">
              2
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#pablo">
              3
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#pablo">
              4
            </a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="navbar-right nav-item">
            <a class="nav-link" href="#">
              <p>Login</p>
            </a>
          </li>
          <li class="navbar-right nav-item">
            <a class="nav-link btn btn-primary" href="#">
              <p>Signup</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
```

Best regards,
KonScyence

**Comment by dragosct10** [comment]
Hi, @KonScyence! To fix it please see the image below, you just have to remove one prop. 

<img width="1216" alt="screenshot 2018-11-26 at 12 31 16" src="https://user-images.githubusercontent.com/17456857/49008755-55577f80-f177-11e8-83e6-73593baa5853.png">

Regards,
Dragos
