### ISSUE TITLE
Help with Login Modal

### ISSUE THREAD

**Issue by MarkG33** [creativetimofficial/ct-now-ui-kit-pro#42]
I'm trying to place the login modal at the top of my page in the nav bar
https://ampli.buzz/signuptest

It launches but there is no interaction - can't fill in fields of close it.

I'm using the exact code from the demos https://demos.creative-tim.com/now-ui-kit-pro/docs/1.0/components/modal.html 

And using Now UI Kit PRO theme

I've been told I can't put modals anywhere except at the bottom of the page before the </body> tag, which seems a bit nonsensical

So how do I really position this modal at the top of my page and have it work?

Thanks

**Comment by dragosct10** [comment]
Hi! I just refresh the page of your project and it seems now it's working fine. I will close now this issue because it's fixed. 

Regards, 
Dragos
