### ISSUE TITLE
now-ui-kit-pro-v1.3.0 index.html has missing div tag

### ISSUE THREAD

**Issue by nicejwjin** [creativetimofficial/ct-now-ui-kit-pro#45]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [O] I am running the latest version
- [O] I checked the documentation and found no answer
- [O] I checked to make sure that this issue has not already been filed
- [O] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting
- index.html should be cleared with no error

# Current Behavior

What is the current behavior?
- builder shows missing div error.

# Failure Information (for bugs)
  <div class="wrapper">
    ...
  </script>
                  <== Missing div position
</body>

If </div> is inserted, error has gone.

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by dragosct10** [comment]
Hi, @nicejwjin! Thank you for using our products and for this observation. We will fix this in the next update. 

Regards, 
Dragos
