### ISSUE TITLE
Upgrading Bootstrap and jQuery

### ISSUE THREAD

**Issue by brunoamaral** [creativetimofficial/ct-now-ui-kit-pro#48]
# Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I was running an audit with Lighthouse, and noticed an error about vulnerabilities

![image](https://user-images.githubusercontent.com/543344/60131043-59409400-9790-11e9-8cda-c68f2f5f005d.png)

# Current Behavior

Now UI Kit Pro is running old versions of Bootstrap and jQuery. New versions of these libraries have fixed these issues.

Can I upgrade them myself without breaking the UI Kit ?

# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. open Dev tools
2. Select audits
3. Run an audit for best practices

## Context

* Device: Not relevant
* Operating System: Not relevant
* Browser and Version: Not relevant

**Comment by dragosct10** [comment]
Hi, @brunoamaral! Thank you for using our products. Please take the latest version of the product, because we updated all these frameworks and plugins. 

Regards, 
Dragos

**Comment by brunoamaral** [comment]
@dragosct10 thanks for the quick reply. I checked the original zip file again and it was using the most recent versions of the libraries, but they weren't upgraded in the production version. It's working now :)
