### ISSUE TITLE
Mobile menu fails at second try

### ISSUE THREAD

**Issue by brunoamaral** [creativetimofficial/ct-now-ui-kit-pro#49]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Menu should always open when you click the hamburger icon

# Current Behavior

After opening the first time, and trying to open a second time, the menu disappears. 

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

![ios_bug_gif](https://user-images.githubusercontent.com/543344/60664472-f028e280-9e59-11e9-872a-e6a5f4d01f5a.gif)

## Context

* Device: iPhone XR
* Operating System: iOS 12
* Browser and Version: Safari

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by dragosct10** [comment]
Hi, @brunoamaral! Thank you for using our products. For the moment to fix the issue please go in `assets/scss/now-ui-kit/mixins/_navbar.scss` and there please search for the navbar-collapse() mixin and inside the mixin you will find the .navbar-collapse class and put` !important` on the `display:block;` property. In the next update, we will fix this issue.

Regards,
Dragos

**Comment by brunoamaral** [comment]
Thank you @dragosct10, I've applied the fix and confirmed it works.
