### ISSUE TITLE
on mobile, blog post with share buttons and without 'read article' results in misaligned buttons

### ISSUE THREAD

**Issue by brunoamaral** [creativetimofficial/ct-now-ui-kit-pro#50]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Social media share buttons in header should align properly in all screen sizes
![image](https://user-images.githubusercontent.com/543344/61133562-948fd200-a4b5-11e9-9541-8ecae9f2b896.png)

# Current Behavior

On mobile:

<img width="421" alt="image-20190712144942597" src="https://user-images.githubusercontent.com/543344/61133606-a83b3880-a4b5-11e9-84a3-dc87063d1570.png">

# Failure Information (for bugs)

This is fixed by removing display block:

```css
@media screen and (max-width: 576px)
.blog-post .button-container>.btn:first-child {
    /* display: block; */
    }
```

## Steps to Reproduce

1. Open the blog-post example with share buttons
2. Remove the first button, called "read article"
3. Resize to mobile

**Comment by dragosct10** [comment]
Hi, @brunoamaral! Yes, you are right this is a responsive issue. A better way to fix this issue, in my opinion, would be to put half of the buttons in another row with col-6 and another half also in a row with a col-6, so in this way, the buttons will stay aligned. Anyway, we will fix this in the next update. 

Regards, 
Dragos
