### ISSUE TITLE
not able to compile scss file 

### ISSUE THREAD

**Issue by Jimmi08** [creativetimofficial/ct-now-ui-kit-pro#52]
I use latest version 1.3.0
I am not able to compile scss because of error:
![image](https://user-images.githubusercontent.com/5429548/63431035-41972c00-c41e-11e9-8a54-ad19ded8ebbf.png)

After fixing those paths, scss file is able to be compiled only with npm/gulp, but not with koala

```
Error: Base-level rules cannot contain the parent-selector-referencing character '&'.
        on line 2 of xxx/assets/scss/now-ui-kit/mixins/_navbar.scss, in `navbar-responsive'
        from line 231 of xxx/assets/scss/now-ui-kit/mixins/_navbar.scss, in `navbar-collapse'
        from line 2 of xxx/assets/scss/now-ui-kit/_responsive.scss
        from line 86 of xxx/assets/scss\now-ui-kit.scss
```
Thank you

**Comment by dragosct10** [comment]
Hi, @Jimmi08! Thank you for using our products. Please go to assets/scss/now-ui-kit/_mixins.scss and remove the prefix `../core/`. 

Regards, 
Dragos

**Comment by Jimmi08** [comment]
Thank you, I was able to fix it this way.. But that koala issue stays.
