### ISSUE TITLE
on mobile only just part of navigation is displayed

### ISSUE THREAD

**Issue by Jimmi08** [creativetimofficial/ct-now-ui-kit-pro#53]
Check this please with your example Header 1 or 2  (navigation with logo, centered menu and right part)

this one:
![image](https://user-images.githubusercontent.com/5429548/63672778-06607880-c7e3-11e9-8b07-939d58254c8b.png)

for centered menu and right part you are using navba-nav class.  But on mobile only one navbar-nav is displayed.  It's not big issue with social links, but if you have there other links set (registration), it is problem. And because you use special script for mobile display, it's not so easy to fix for me.

```
            <div class="collapse navbar-collapse">
              <ul class="navbar-nav mx-auto">
     -- content -- 
              </ul>
              <ul class="nav navbar-nav navbar-right">
      -- content -- 
              </ul>
            </div>
```

Thanks

PS. In your navigation components, this example is not listed.

**Comment by dragosct10** [comment]
Hi, @Jimmi08! Thank you for using our products. You are right, this is an issue and we will fix in the next update, which is planning to be in at the end of this week. 

Regards,
Dragos

**Comment by Jimmi08** [comment]
Hi, @dragosct10 thank you for quick answer. It would be great. And if you can, could you add example with user box? I tried to use example from dashboard pro, but it doesn't fit exactly.  Bootstrap3 themes had this. 
I have this on mind:

![image](https://user-images.githubusercontent.com/5429548/63676808-07e26e80-c7ec-11e9-87c4-4fadb4027a33.png)

Thank you.

**Comment by dragosct10** [comment]
@Jimmi08 we usually wait for a minimum 5 requests until we implement some new features in the product. 

Regards, 
Dragos

**Comment by Jimmi08** [comment]
> @Jimmi08 we usually wait for a minimum 5 requests until we implement some new features in the product.
> 
> Regards,
> Dragos

Thanks, I will create a new issue with the feature request for this. Then you can close this after next update.

**Comment by master0v** [comment]
I am running UIkit 3.4.2 and I am seeing this regression:

https://drive.google.com/file/d/1zQldiMBo9dkmAUsu36fqss0jS9t8mTmb/view?usp=sharing
