### ISSUE TITLE
[Bug] Navbar is briefly shown and then hidden on screen resize to smaller screens.

### ISSUE THREAD

**Issue by b3nja17** [creativetimofficial/ct-now-ui-kit-pro#59]
### Version
Latest
### Reproduction link
https://demos.creative-tim.com/now-ui-kit-pro/presentation.html
### Operating System
MacOS Catalina
### Device
MacBook Pro 13
### Browser & Version
Safari, Chrome, Firefox (all newest v)
### Steps to reproduce
1. go to the link (the CT demo for the kit).
2. resize the screen
3. once you hit the 992 px breakpoint and make a smaller screen the nav will switch to mobile but will be shown briefly before hiding.
### What is expected?
I don't want the navbar to show on resize. I just want it to hide.
### What is actually happening?
navbar shows and then is hidden

---
### Solution
I have tried removing different classes but nothing I have found so far works.
### Additional comments
I have tried removing different classes but nothing I have found so far works.

**Comment by dragosct10** [comment]
Hi, @b3nja17! Thank you for using our products. Please, can you show us a video with the bug to be more specific because I can't reproduce the issue? 

Regards,
Dragos

**Comment by b3nja17** [comment]
Thanks for the quick response @dragosct10. Uploading a gif to show the functionality. Ideally the navbar would hide on default (not show briefly as shown in the gif) when the screen hits the break point. 
![trim](https://user-images.githubusercontent.com/9846465/73317768-95822880-427a-11ea-986c-787ebb00318a.gif)

**Comment by dragosct10** [comment]
Hi, @b3nja17! Sorry for the late response. The cause of this problem is the transition property on the `.navbar-collapse` div and you can remove it from CSS and you can add this transition only on click to `.navbar-toggler` and then will work smoothie. 

Regards,
Dragos

**Comment by b3nja17** [comment]
@dragosct10 thanks for the response. I've tried removing the css from the .navbar-collapse class and adding the following code before like you recommend but I'm still having the same problem. 
`$(document).on('click', 'button.navbar-toggler', function() {
    if ($(window).width() <= 991){
    $("button.navbar-toggler").css({'-webkit-transition': 'all 0.5s cubic-bezier(0.685, 0.0473, 0.346, 1)',
        '-moz-transition': 'all 0.5s cubic-bezier(0.685, 0.0473, 0.346, 1)',
        '-o-transition': 'all 0.5s cubic-bezier(0.685, 0.0473, 0.346, 1)',
        '-ms-transition': 'all 0.5s cubic-bezier(0.685, 0.0473, 0.346, 1)',
        'transition': 'all 0.5s cubic-bezier(0.685, 0.0473, 0.346, 1)'})
    }
});`

**Comment by dragosct10** [comment]
Hi! I will take a look and I will help you. I will return with an answer for you. 

Regards,
Dragos

**Comment by dragosct10** [comment]
Hi! Please put this code in your js file and be sure that the transition from .navbar-collapse CSS is removed. 

```js
var transitionValue = 'all 0.5s cubic-bezier(0.685, 0.0473, 0.346, 1)'
var transitionProp = 'transition'

$(document).on('click', '.navbar-toggler', function() {
  if ($(window).width() <= 991) {
    $(".navbar-collapse").css(transitionProp, transitionValue)
  }
});

$(window).on('resize', function(){
  if ($(window).width() > 991) {
    $(".navbar-collapse").css(transitionProp,'')
  } else {
    $(".navbar-collapse").css(transitionProp,transitionValue)
  }
});

Regards,
Dragos
```

**Comment by b3nja17** [comment]
Thanks @dragosct10, that fixed it.
