### ISSUE TITLE
Sass Error

### ISSUE THREAD

**Issue by danieledandreti** [creativetimofficial/ct-now-ui-kit-pro#61]
Hello

I have the pro version of now ui kit, when I try to compile with codekit it gives me an error that you can see in the image.

With the fre version of now ui kit the compilation is error free.
<img width="1109" alt="Schermata 2020-04-10 alle 00 38 16" src="https://user-images.githubusercontent.com/7130290/78947012-88788580-7ac4-11ea-90eb-850cf7ae6e8d.png">

**Comment by dragosct10** [comment]
Hi, @danieledandreti! Thank you for using our products. Please go in the assets/scss/now-ui-kit/mixins/_navbar.scss on line 2 and remove: 
```
 &.menu-on-left .navbar-translate {
     flex-direction: row-reverse;
 }
```

After that please go below and add this line of code on 234: 

```
.navbar-collapse.menu-on-left .navbar-translate {
      flex-direction: row-reverse;
    }
```

Regards,
Dragos

**Comment by danieledandreti** [comment]
Thanks Dragos, 
there are no errors when compiling the SCSS. :-)
