### ISSUE TITLE
Page header image issue

### ISSUE THREAD

**Issue by Bagmaz** [creativetimofficial/ct-now-ui-kit-pro#7]
![img_36debd537559-1](https://user-images.githubusercontent.com/20259560/35386954-38d89c84-01ce-11e8-85cd-195d41de8b3d.jpeg)

**Comment by dragosct10** [comment]
Hi, @Bagmaz! This is not the same issue that you opened in this [link](https://github.com/creativetimofficial/now-ui-kit-pro/issues/4)? 

Regards, 
Dragos

**Comment by Bagmaz** [comment]
Hi, @dragosct10
Sry, My English is not good.
I use _sections.scss.zip but still having trouble.
I have registration form with 7 fields, Can you give me an example?

**Comment by Bagmaz** [comment]
I fixed it,

<img width="873" alt="screen shot 2018-01-27 at 11 41 41 pm" src="https://user-images.githubusercontent.com/20259560/35477064-d826885c-03bb-11e8-8384-a8adb2c0da6b.png">
