### ISSUE TITLE
Click event disabled

### ISSUE THREAD

**Issue by israelias94** [creativetimofficial/ct-now-ui-kit-pro#8]
On the Login page (example pages), all components appear to have click events disabled. Especially in the form where I need to fill Name and Last Name and the buttons of form itself

![screenshot from 2018-02-23 01-07-14](https://user-images.githubusercontent.com/16140960/36578801-f280ac80-1835-11e8-8bee-1e87b327dc27.png)

**Comment by dragosct10** [comment]
Hi, @israelias94! Thank you for using our product. The problem is that you can't enter text in the inputs or is that another problem? Regards, Dragos

**Comment by israelias94** [comment]
exactly... i can't enter text in the inputs and i can't click on get Started button

**Comment by dragosct10** [comment]
Hi, @israelias94! Yes, you have right. It is a small problem there and we will fix it. You must add on the .page-header .container the property `position: relative;` like in the image. 

<img width="1036" alt="screen shot 2018-02-23 at 20 57 53" src="https://user-images.githubusercontent.com/17456857/36611519-6d349d28-18dc-11e8-9ae6-e30ab9cfb744.png">

Regards,
Dragos

**Comment by israelias94** [comment]
Fixed. Thanks... great support!

**Comment by keshcss** [comment]
> In the login-page.html:161 when I add the clear-filter class all components are focusables.
> 
> ```
> 159:    </nav>
> 160:    
> 161:    <div class="page-header clear-filter" filter-color="orange">
> 162:        <div class="page-header-image" style="background-image:url(../assets/img/login.jpg)"></div>
> 163:        <div class="content">
> 164:            <div class="container">
> ```
> 
> but the background color has changed. What is the error?

Reply : Can i know why the "filter-color 'orange' cannot be changed? Like if i changed it to "filter-color 'red'" it doesnt work
