### ISSUE TITLE
Navbar becomes transparent without navbar-transparent

### ISSUE THREAD

**Issue by israelias94** [creativetimofficial/ct-now-ui-kit-pro#9]
When i put a navbar without navbar-transparent class like that
```
<nav class="navbar navbar-expand-lg bg-white fixed-top " color-on-scroll="500">
```
but in my wrapper div I have the next header
```
<div class="wrapper">
  <div class="page-header">
```

Then the navbar is not transparent at the beginning of the page but if I scroll down and go back to the beginning... the navbar always becomes transparent. but if I add page-header-small on my div like that:
```
<div class="wrapper">
  <div class="page-header page-header-small">
```

Then the navbar works well and never becomes transparent.
Is it a bug?  (I based on the template example.)

**Comment by dragosct10** [comment]
Hi, @israelias94! The navbar was set default to be transparent and also the javascript is made in this way, so probably this is the reason. It's not a problem if you want to turn of this feature and want to have the navbar coloured anytime you can go in your html page and remove the attribute `color-on-scroll` and in this way the javascript will not work anymore and remove also the `navbar-transparent` class and you will have a coloured navbar. 

Regards,
Dragos
